-- Reverse Engineering Logs table for storing prompt reverse engineering results
CREATE TABLE IF NOT EXISTS reverse_engineering_logs (
    -- 1. Basic identification
    id TEXT PRIMARY KEY,  -- UUID generated by application
    user_id TEXT NOT NULL,
    created_at TEXT DEFAULT (datetime('now')),

    -- 2. Article metadata
    article_title TEXT,
    article_url TEXT,
    original_content TEXT,

    -- 3. Classification and results
    genre_category TEXT,  -- NARRATIVE, ACADEMIC, COPYWRITING, NEWS, SOCIAL
    reverse_result_json TEXT,  -- Full structured reverse result (JSON stored as TEXT)
    final_system_prompt TEXT,  -- Extracted final prompt for easy retrieval

    -- 4. Linguistic metrics
    metric_burstiness REAL,
    metric_ttr REAL,
    metric_avg_sent_len REAL,

    -- 5. Audit and cost tracking
    model_name TEXT,  -- e.g. 'deepseek-chat'
    total_tokens INTEGER,
    cost_estimated_usd REAL,
    n8n_execution_id TEXT,  -- For tracing errors in n8n
    status TEXT DEFAULT 'SUCCESS'
);

-- Indexes for query optimization
CREATE INDEX IF NOT EXISTS idx_re_logs_user_id ON reverse_engineering_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_re_logs_genre ON reverse_engineering_logs(genre_category);
CREATE INDEX IF NOT EXISTS idx_re_logs_created_at ON reverse_engineering_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_re_logs_status ON reverse_engineering_logs(status);
