/* eslint-disable */
// Auto-generated by scripts/generate-katex-inline-styles.ts
export interface KatexInlineRule {
  classes: string[]
  tag?: string
  style: string
  requiresKatex: boolean
}

export const KATEX_INLINE_RULES: KatexInlineRule[] = [
  {
    "classes": [
      "katex"
    ],
    "style": "font:normal 1.21em KaTeX_Main,Times New Roman,serif; line-height:1.2; text-indent:0; text-rendering:auto; display:block; text-align:center; white-space:nowrap; padding-left:2em; text-align:left",
    "requiresKatex": true
  },
  {
    "classes": [
      "katex-version"
    ],
    "style": "content:\"0.16.27\"",
    "requiresKatex": true
  },
  {
    "classes": [
      "katex-mathml"
    ],
    "style": "clip:rect(1px,1px,1px,1px); border:0; height:1px; overflow:hidden; padding:0; position:absolute; width:1px",
    "requiresKatex": true
  },
  {
    "classes": [
      "newline"
    ],
    "style": "display:block",
    "requiresKatex": true
  },
  {
    "classes": [
      "base"
    ],
    "style": "position:relative; white-space:nowrap; width:-webkit-min-content; width:-moz-min-content; width:min-content; display:inline-block",
    "requiresKatex": true
  },
  {
    "classes": [
      "strut"
    ],
    "style": "display:inline-block",
    "requiresKatex": true
  },
  {
    "classes": [
      "textbf"
    ],
    "style": "font-weight:700",
    "requiresKatex": true
  },
  {
    "classes": [
      "textit"
    ],
    "style": "font-style:italic",
    "requiresKatex": true
  },
  {
    "classes": [
      "textrm"
    ],
    "style": "font-family:KaTeX_Main",
    "requiresKatex": true
  },
  {
    "classes": [
      "textsf"
    ],
    "style": "font-family:KaTeX_SansSerif; font-family:KaTeX_SansSerif",
    "requiresKatex": true
  },
  {
    "classes": [
      "texttt"
    ],
    "style": "font-family:KaTeX_Typewriter",
    "requiresKatex": true
  },
  {
    "classes": [
      "mathnormal"
    ],
    "style": "font-family:KaTeX_Math; font-style:italic",
    "requiresKatex": true
  },
  {
    "classes": [
      "mathit"
    ],
    "style": "font-family:KaTeX_Main; font-style:italic",
    "requiresKatex": true
  },
  {
    "classes": [
      "mathrm"
    ],
    "style": "font-style:normal",
    "requiresKatex": true
  },
  {
    "classes": [
      "mathbf"
    ],
    "style": "font-family:KaTeX_Main; font-weight:700",
    "requiresKatex": true
  },
  {
    "classes": [
      "boldsymbol"
    ],
    "style": "font-family:KaTeX_Math; font-style:italic; font-weight:700",
    "requiresKatex": true
  },
  {
    "classes": [
      "amsrm"
    ],
    "style": "font-family:KaTeX_AMS",
    "requiresKatex": true
  },
  {
    "classes": [
      "mathbb"
    ],
    "style": "font-family:KaTeX_AMS",
    "requiresKatex": true
  },
  {
    "classes": [
      "textbb"
    ],
    "style": "font-family:KaTeX_AMS",
    "requiresKatex": true
  },
  {
    "classes": [
      "mathcal"
    ],
    "style": "font-family:KaTeX_Caligraphic",
    "requiresKatex": true
  },
  {
    "classes": [
      "mathfrak"
    ],
    "style": "font-family:KaTeX_Fraktur",
    "requiresKatex": true
  },
  {
    "classes": [
      "textfrak"
    ],
    "style": "font-family:KaTeX_Fraktur",
    "requiresKatex": true
  },
  {
    "classes": [
      "mathboldfrak"
    ],
    "style": "font-family:KaTeX_Fraktur; font-weight:700",
    "requiresKatex": true
  },
  {
    "classes": [
      "textboldfrak"
    ],
    "style": "font-family:KaTeX_Fraktur; font-weight:700",
    "requiresKatex": true
  },
  {
    "classes": [
      "mathtt"
    ],
    "style": "font-family:KaTeX_Typewriter",
    "requiresKatex": true
  },
  {
    "classes": [
      "mathscr"
    ],
    "style": "font-family:KaTeX_Script",
    "requiresKatex": true
  },
  {
    "classes": [
      "textscr"
    ],
    "style": "font-family:KaTeX_Script",
    "requiresKatex": true
  },
  {
    "classes": [
      "mathsf"
    ],
    "style": "font-family:KaTeX_SansSerif",
    "requiresKatex": true
  },
  {
    "classes": [
      "mathboldsf"
    ],
    "style": "font-family:KaTeX_SansSerif; font-weight:700",
    "requiresKatex": true
  },
  {
    "classes": [
      "textboldsf"
    ],
    "style": "font-family:KaTeX_SansSerif; font-weight:700",
    "requiresKatex": true
  },
  {
    "classes": [
      "mathitsf"
    ],
    "style": "font-family:KaTeX_SansSerif; font-style:italic",
    "requiresKatex": true
  },
  {
    "classes": [
      "mathsfit"
    ],
    "style": "font-family:KaTeX_SansSerif; font-style:italic",
    "requiresKatex": true
  },
  {
    "classes": [
      "textitsf"
    ],
    "style": "font-family:KaTeX_SansSerif; font-style:italic",
    "requiresKatex": true
  },
  {
    "classes": [
      "mainrm"
    ],
    "style": "font-family:KaTeX_Main; font-style:normal",
    "requiresKatex": true
  },
  {
    "classes": [
      "vlist-t"
    ],
    "style": "border-collapse:collapse; display:inline-table; table-layout:fixed; text-align:center; text-align:center; text-align:center; text-align:left; text-align:right",
    "requiresKatex": true
  },
  {
    "classes": [
      "vlist-r"
    ],
    "style": "display:table-row",
    "requiresKatex": true
  },
  {
    "classes": [
      "vlist"
    ],
    "style": "display:table-cell; position:relative; vertical-align:bottom",
    "requiresKatex": true
  },
  {
    "classes": [],
    "tag": "span",
    "style": "display:block; height:0; position:relative; display:inline-block; text-align:center; margin-left:-50%; margin-right:50%; font-family:KaTeX_Size1; font-family:KaTeX_Size4",
    "requiresKatex": true
  },
  {
    "classes": [
      "pstrut"
    ],
    "style": "overflow:hidden; width:0",
    "requiresKatex": true
  },
  {
    "classes": [
      "vlist-t2"
    ],
    "style": "margin-right:-2px",
    "requiresKatex": true
  },
  {
    "classes": [
      "vlist-s"
    ],
    "style": "display:table-cell; font-size:1px; min-width:2px; vertical-align:bottom; width:2px",
    "requiresKatex": true
  },
  {
    "classes": [
      "vbox"
    ],
    "style": "align-items:baseline; display:inline-flex; flex-direction:column",
    "requiresKatex": true
  },
  {
    "classes": [
      "hbox"
    ],
    "style": "width:100%; display:inline-flex; flex-direction:row",
    "requiresKatex": true
  },
  {
    "classes": [
      "thinbox"
    ],
    "style": "display:inline-flex; flex-direction:row; max-width:0; width:0",
    "requiresKatex": true
  },
  {
    "classes": [
      "msupsub"
    ],
    "style": "text-align:left",
    "requiresKatex": true
  },
  {
    "classes": [
      "frac-line"
    ],
    "style": "border-bottom-style:solid; display:inline-block; width:100%; min-height:1px",
    "requiresKatex": true
  },
  {
    "classes": [
      "hdashline"
    ],
    "style": "min-height:1px; border-bottom-style:dashed; display:inline-block; width:100%",
    "requiresKatex": true
  },
  {
    "classes": [
      "hline"
    ],
    "style": "min-height:1px; border-bottom-style:solid; display:inline-block; width:100%",
    "requiresKatex": true
  },
  {
    "classes": [
      "overline-line"
    ],
    "style": "min-height:1px; border-bottom-style:solid; display:inline-block; width:100%",
    "requiresKatex": true
  },
  {
    "classes": [
      "rule"
    ],
    "style": "min-height:1px; border:0 solid; display:inline-block; position:relative",
    "requiresKatex": true
  },
  {
    "classes": [
      "underline-line"
    ],
    "style": "min-height:1px; border-bottom-style:solid; display:inline-block; width:100%",
    "requiresKatex": true
  },
  {
    "classes": [
      "mspace"
    ],
    "style": "display:inline-block",
    "requiresKatex": true
  },
  {
    "classes": [
      "clap"
    ],
    "style": "position:relative; width:0",
    "requiresKatex": true
  },
  {
    "classes": [
      "llap"
    ],
    "style": "position:relative; width:0",
    "requiresKatex": true
  },
  {
    "classes": [
      "rlap"
    ],
    "style": "position:relative; width:0",
    "requiresKatex": true
  },
  {
    "classes": [
      "inner"
    ],
    "style": "position:absolute; position:absolute; position:absolute; right:0; left:0; left:0",
    "requiresKatex": true
  },
  {
    "classes": [
      "fix"
    ],
    "style": "display:inline-block; display:inline-block; display:inline-block",
    "requiresKatex": true
  },
  {
    "classes": [
      "root"
    ],
    "style": "margin-left:.2777777778em; margin-right:-.5555555556em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size1",
      "size1"
    ],
    "style": "font-size:1em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size1",
      "size1"
    ],
    "style": "font-size:1em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size1",
      "size2"
    ],
    "style": "font-size:1.2em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size1",
      "size2"
    ],
    "style": "font-size:1.2em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size1",
      "size3"
    ],
    "style": "font-size:1.4em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size1",
      "size3"
    ],
    "style": "font-size:1.4em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size1",
      "size4"
    ],
    "style": "font-size:1.6em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size1",
      "size4"
    ],
    "style": "font-size:1.6em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size1",
      "size5"
    ],
    "style": "font-size:1.8em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size1",
      "size5"
    ],
    "style": "font-size:1.8em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size1",
      "size6"
    ],
    "style": "font-size:2em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size1",
      "size6"
    ],
    "style": "font-size:2em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size1",
      "size7"
    ],
    "style": "font-size:2.4em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size1",
      "size7"
    ],
    "style": "font-size:2.4em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size1",
      "size8"
    ],
    "style": "font-size:2.88em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size1",
      "size8"
    ],
    "style": "font-size:2.88em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size1",
      "size9"
    ],
    "style": "font-size:3.456em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size1",
      "size9"
    ],
    "style": "font-size:3.456em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size1",
      "size10"
    ],
    "style": "font-size:4.148em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size1",
      "size10"
    ],
    "style": "font-size:4.148em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size1",
      "size11"
    ],
    "style": "font-size:4.976em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size1",
      "size11"
    ],
    "style": "font-size:4.976em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size2",
      "size1"
    ],
    "style": "font-size:.8333333333em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size2",
      "size1"
    ],
    "style": "font-size:.8333333333em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size2",
      "size2"
    ],
    "style": "font-size:1em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size2",
      "size2"
    ],
    "style": "font-size:1em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size2",
      "size3"
    ],
    "style": "font-size:1.1666666667em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size2",
      "size3"
    ],
    "style": "font-size:1.1666666667em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size2",
      "size4"
    ],
    "style": "font-size:1.3333333333em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size2",
      "size4"
    ],
    "style": "font-size:1.3333333333em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size2",
      "size5"
    ],
    "style": "font-size:1.5em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size2",
      "size5"
    ],
    "style": "font-size:1.5em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size2",
      "size6"
    ],
    "style": "font-size:1.6666666667em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size2",
      "size6"
    ],
    "style": "font-size:1.6666666667em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size2",
      "size7"
    ],
    "style": "font-size:2em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size2",
      "size7"
    ],
    "style": "font-size:2em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size2",
      "size8"
    ],
    "style": "font-size:2.4em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size2",
      "size8"
    ],
    "style": "font-size:2.4em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size2",
      "size9"
    ],
    "style": "font-size:2.88em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size2",
      "size9"
    ],
    "style": "font-size:2.88em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size2",
      "size10"
    ],
    "style": "font-size:3.4566666667em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size2",
      "size10"
    ],
    "style": "font-size:3.4566666667em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size2",
      "size11"
    ],
    "style": "font-size:4.1466666667em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size2",
      "size11"
    ],
    "style": "font-size:4.1466666667em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size3",
      "size1"
    ],
    "style": "font-size:.7142857143em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size3",
      "size1"
    ],
    "style": "font-size:.7142857143em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size3",
      "size2"
    ],
    "style": "font-size:.8571428571em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size3",
      "size2"
    ],
    "style": "font-size:.8571428571em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size3",
      "size3"
    ],
    "style": "font-size:1em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size3",
      "size3"
    ],
    "style": "font-size:1em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size3",
      "size4"
    ],
    "style": "font-size:1.1428571429em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size3",
      "size4"
    ],
    "style": "font-size:1.1428571429em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size3",
      "size5"
    ],
    "style": "font-size:1.2857142857em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size3",
      "size5"
    ],
    "style": "font-size:1.2857142857em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size3",
      "size6"
    ],
    "style": "font-size:1.4285714286em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size3",
      "size6"
    ],
    "style": "font-size:1.4285714286em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size3",
      "size7"
    ],
    "style": "font-size:1.7142857143em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size3",
      "size7"
    ],
    "style": "font-size:1.7142857143em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size3",
      "size8"
    ],
    "style": "font-size:2.0571428571em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size3",
      "size8"
    ],
    "style": "font-size:2.0571428571em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size3",
      "size9"
    ],
    "style": "font-size:2.4685714286em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size3",
      "size9"
    ],
    "style": "font-size:2.4685714286em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size3",
      "size10"
    ],
    "style": "font-size:2.9628571429em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size3",
      "size10"
    ],
    "style": "font-size:2.9628571429em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size3",
      "size11"
    ],
    "style": "font-size:3.5542857143em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size3",
      "size11"
    ],
    "style": "font-size:3.5542857143em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size4",
      "size1"
    ],
    "style": "font-size:.625em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size4",
      "size1"
    ],
    "style": "font-size:.625em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size4",
      "size2"
    ],
    "style": "font-size:.75em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size4",
      "size2"
    ],
    "style": "font-size:.75em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size4",
      "size3"
    ],
    "style": "font-size:.875em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size4",
      "size3"
    ],
    "style": "font-size:.875em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size4",
      "size4"
    ],
    "style": "font-size:1em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size4",
      "size4"
    ],
    "style": "font-size:1em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size4",
      "size5"
    ],
    "style": "font-size:1.125em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size4",
      "size5"
    ],
    "style": "font-size:1.125em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size4",
      "size6"
    ],
    "style": "font-size:1.25em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size4",
      "size6"
    ],
    "style": "font-size:1.25em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size4",
      "size7"
    ],
    "style": "font-size:1.5em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size4",
      "size7"
    ],
    "style": "font-size:1.5em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size4",
      "size8"
    ],
    "style": "font-size:1.8em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size4",
      "size8"
    ],
    "style": "font-size:1.8em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size4",
      "size9"
    ],
    "style": "font-size:2.16em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size4",
      "size9"
    ],
    "style": "font-size:2.16em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size4",
      "size10"
    ],
    "style": "font-size:2.5925em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size4",
      "size10"
    ],
    "style": "font-size:2.5925em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size4",
      "size11"
    ],
    "style": "font-size:3.11em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size4",
      "size11"
    ],
    "style": "font-size:3.11em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size5",
      "size1"
    ],
    "style": "font-size:.5555555556em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size5",
      "size1"
    ],
    "style": "font-size:.5555555556em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size5",
      "size2"
    ],
    "style": "font-size:.6666666667em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size5",
      "size2"
    ],
    "style": "font-size:.6666666667em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size5",
      "size3"
    ],
    "style": "font-size:.7777777778em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size5",
      "size3"
    ],
    "style": "font-size:.7777777778em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size5",
      "size4"
    ],
    "style": "font-size:.8888888889em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size5",
      "size4"
    ],
    "style": "font-size:.8888888889em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size5",
      "size5"
    ],
    "style": "font-size:1em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size5",
      "size5"
    ],
    "style": "font-size:1em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size5",
      "size6"
    ],
    "style": "font-size:1.1111111111em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size5",
      "size6"
    ],
    "style": "font-size:1.1111111111em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size5",
      "size7"
    ],
    "style": "font-size:1.3333333333em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size5",
      "size7"
    ],
    "style": "font-size:1.3333333333em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size5",
      "size8"
    ],
    "style": "font-size:1.6em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size5",
      "size8"
    ],
    "style": "font-size:1.6em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size5",
      "size9"
    ],
    "style": "font-size:1.92em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size5",
      "size9"
    ],
    "style": "font-size:1.92em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size5",
      "size10"
    ],
    "style": "font-size:2.3044444444em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size5",
      "size10"
    ],
    "style": "font-size:2.3044444444em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size5",
      "size11"
    ],
    "style": "font-size:2.7644444444em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size5",
      "size11"
    ],
    "style": "font-size:2.7644444444em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size6",
      "size1"
    ],
    "style": "font-size:.5em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size6",
      "size1"
    ],
    "style": "font-size:.5em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size6",
      "size2"
    ],
    "style": "font-size:.6em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size6",
      "size2"
    ],
    "style": "font-size:.6em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size6",
      "size3"
    ],
    "style": "font-size:.7em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size6",
      "size3"
    ],
    "style": "font-size:.7em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size6",
      "size4"
    ],
    "style": "font-size:.8em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size6",
      "size4"
    ],
    "style": "font-size:.8em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size6",
      "size5"
    ],
    "style": "font-size:.9em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size6",
      "size5"
    ],
    "style": "font-size:.9em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size6",
      "size6"
    ],
    "style": "font-size:1em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size6",
      "size6"
    ],
    "style": "font-size:1em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size6",
      "size7"
    ],
    "style": "font-size:1.2em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size6",
      "size7"
    ],
    "style": "font-size:1.2em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size6",
      "size8"
    ],
    "style": "font-size:1.44em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size6",
      "size8"
    ],
    "style": "font-size:1.44em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size6",
      "size9"
    ],
    "style": "font-size:1.728em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size6",
      "size9"
    ],
    "style": "font-size:1.728em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size6",
      "size10"
    ],
    "style": "font-size:2.074em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size6",
      "size10"
    ],
    "style": "font-size:2.074em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size6",
      "size11"
    ],
    "style": "font-size:2.488em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size6",
      "size11"
    ],
    "style": "font-size:2.488em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size7",
      "size1"
    ],
    "style": "font-size:.4166666667em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size7",
      "size1"
    ],
    "style": "font-size:.4166666667em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size7",
      "size2"
    ],
    "style": "font-size:.5em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size7",
      "size2"
    ],
    "style": "font-size:.5em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size7",
      "size3"
    ],
    "style": "font-size:.5833333333em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size7",
      "size3"
    ],
    "style": "font-size:.5833333333em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size7",
      "size4"
    ],
    "style": "font-size:.6666666667em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size7",
      "size4"
    ],
    "style": "font-size:.6666666667em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size7",
      "size5"
    ],
    "style": "font-size:.75em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size7",
      "size5"
    ],
    "style": "font-size:.75em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size7",
      "size6"
    ],
    "style": "font-size:.8333333333em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size7",
      "size6"
    ],
    "style": "font-size:.8333333333em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size7",
      "size7"
    ],
    "style": "font-size:1em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size7",
      "size7"
    ],
    "style": "font-size:1em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size7",
      "size8"
    ],
    "style": "font-size:1.2em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size7",
      "size8"
    ],
    "style": "font-size:1.2em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size7",
      "size9"
    ],
    "style": "font-size:1.44em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size7",
      "size9"
    ],
    "style": "font-size:1.44em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size7",
      "size10"
    ],
    "style": "font-size:1.7283333333em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size7",
      "size10"
    ],
    "style": "font-size:1.7283333333em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size7",
      "size11"
    ],
    "style": "font-size:2.0733333333em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size7",
      "size11"
    ],
    "style": "font-size:2.0733333333em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size8",
      "size1"
    ],
    "style": "font-size:.3472222222em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size8",
      "size1"
    ],
    "style": "font-size:.3472222222em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size8",
      "size2"
    ],
    "style": "font-size:.4166666667em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size8",
      "size2"
    ],
    "style": "font-size:.4166666667em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size8",
      "size3"
    ],
    "style": "font-size:.4861111111em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size8",
      "size3"
    ],
    "style": "font-size:.4861111111em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size8",
      "size4"
    ],
    "style": "font-size:.5555555556em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size8",
      "size4"
    ],
    "style": "font-size:.5555555556em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size8",
      "size5"
    ],
    "style": "font-size:.625em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size8",
      "size5"
    ],
    "style": "font-size:.625em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size8",
      "size6"
    ],
    "style": "font-size:.6944444444em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size8",
      "size6"
    ],
    "style": "font-size:.6944444444em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size8",
      "size7"
    ],
    "style": "font-size:.8333333333em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size8",
      "size7"
    ],
    "style": "font-size:.8333333333em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size8",
      "size8"
    ],
    "style": "font-size:1em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size8",
      "size8"
    ],
    "style": "font-size:1em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size8",
      "size9"
    ],
    "style": "font-size:1.2em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size8",
      "size9"
    ],
    "style": "font-size:1.2em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size8",
      "size10"
    ],
    "style": "font-size:1.4402777778em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size8",
      "size10"
    ],
    "style": "font-size:1.4402777778em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size8",
      "size11"
    ],
    "style": "font-size:1.7277777778em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size8",
      "size11"
    ],
    "style": "font-size:1.7277777778em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size9",
      "size1"
    ],
    "style": "font-size:.2893518519em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size9",
      "size1"
    ],
    "style": "font-size:.2893518519em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size9",
      "size2"
    ],
    "style": "font-size:.3472222222em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size9",
      "size2"
    ],
    "style": "font-size:.3472222222em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size9",
      "size3"
    ],
    "style": "font-size:.4050925926em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size9",
      "size3"
    ],
    "style": "font-size:.4050925926em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size9",
      "size4"
    ],
    "style": "font-size:.462962963em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size9",
      "size4"
    ],
    "style": "font-size:.462962963em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size9",
      "size5"
    ],
    "style": "font-size:.5208333333em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size9",
      "size5"
    ],
    "style": "font-size:.5208333333em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size9",
      "size6"
    ],
    "style": "font-size:.5787037037em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size9",
      "size6"
    ],
    "style": "font-size:.5787037037em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size9",
      "size7"
    ],
    "style": "font-size:.6944444444em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size9",
      "size7"
    ],
    "style": "font-size:.6944444444em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size9",
      "size8"
    ],
    "style": "font-size:.8333333333em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size9",
      "size8"
    ],
    "style": "font-size:.8333333333em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size9",
      "size9"
    ],
    "style": "font-size:1em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size9",
      "size9"
    ],
    "style": "font-size:1em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size9",
      "size10"
    ],
    "style": "font-size:1.2002314815em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size9",
      "size10"
    ],
    "style": "font-size:1.2002314815em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size9",
      "size11"
    ],
    "style": "font-size:1.4398148148em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size9",
      "size11"
    ],
    "style": "font-size:1.4398148148em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size10",
      "size1"
    ],
    "style": "font-size:.2410800386em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size10",
      "size1"
    ],
    "style": "font-size:.2410800386em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size10",
      "size2"
    ],
    "style": "font-size:.2892960463em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size10",
      "size2"
    ],
    "style": "font-size:.2892960463em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size10",
      "size3"
    ],
    "style": "font-size:.337512054em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size10",
      "size3"
    ],
    "style": "font-size:.337512054em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size10",
      "size4"
    ],
    "style": "font-size:.3857280617em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size10",
      "size4"
    ],
    "style": "font-size:.3857280617em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size10",
      "size5"
    ],
    "style": "font-size:.4339440694em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size10",
      "size5"
    ],
    "style": "font-size:.4339440694em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size10",
      "size6"
    ],
    "style": "font-size:.4821600771em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size10",
      "size6"
    ],
    "style": "font-size:.4821600771em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size10",
      "size7"
    ],
    "style": "font-size:.5785920926em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size10",
      "size7"
    ],
    "style": "font-size:.5785920926em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size10",
      "size8"
    ],
    "style": "font-size:.6943105111em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size10",
      "size8"
    ],
    "style": "font-size:.6943105111em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size10",
      "size9"
    ],
    "style": "font-size:.8331726133em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size10",
      "size9"
    ],
    "style": "font-size:.8331726133em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size10",
      "size10"
    ],
    "style": "font-size:1em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size10",
      "size10"
    ],
    "style": "font-size:1em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size10",
      "size11"
    ],
    "style": "font-size:1.1996142719em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size10",
      "size11"
    ],
    "style": "font-size:1.1996142719em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size11",
      "size1"
    ],
    "style": "font-size:.2009646302em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size11",
      "size1"
    ],
    "style": "font-size:.2009646302em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size11",
      "size2"
    ],
    "style": "font-size:.2411575563em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size11",
      "size2"
    ],
    "style": "font-size:.2411575563em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size11",
      "size3"
    ],
    "style": "font-size:.2813504823em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size11",
      "size3"
    ],
    "style": "font-size:.2813504823em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size11",
      "size4"
    ],
    "style": "font-size:.3215434084em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size11",
      "size4"
    ],
    "style": "font-size:.3215434084em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size11",
      "size5"
    ],
    "style": "font-size:.3617363344em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size11",
      "size5"
    ],
    "style": "font-size:.3617363344em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size11",
      "size6"
    ],
    "style": "font-size:.4019292605em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size11",
      "size6"
    ],
    "style": "font-size:.4019292605em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size11",
      "size7"
    ],
    "style": "font-size:.4823151125em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size11",
      "size7"
    ],
    "style": "font-size:.4823151125em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size11",
      "size8"
    ],
    "style": "font-size:.578778135em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size11",
      "size8"
    ],
    "style": "font-size:.578778135em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size11",
      "size9"
    ],
    "style": "font-size:.6945337621em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size11",
      "size9"
    ],
    "style": "font-size:.6945337621em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size11",
      "size10"
    ],
    "style": "font-size:.8336012862em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size11",
      "size10"
    ],
    "style": "font-size:.8336012862em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fontsize-ensurer",
      "reset-size11",
      "size11"
    ],
    "style": "font-size:1em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sizing",
      "reset-size11",
      "size11"
    ],
    "style": "font-size:1em",
    "requiresKatex": true
  },
  {
    "classes": [
      "delimsizing",
      "size1"
    ],
    "style": "font-family:KaTeX_Size1",
    "requiresKatex": true
  },
  {
    "classes": [
      "delimsizing",
      "size2"
    ],
    "style": "font-family:KaTeX_Size2",
    "requiresKatex": true
  },
  {
    "classes": [
      "delimsizing",
      "size3"
    ],
    "style": "font-family:KaTeX_Size3",
    "requiresKatex": true
  },
  {
    "classes": [
      "delimsizing",
      "size4"
    ],
    "style": "font-family:KaTeX_Size4",
    "requiresKatex": true
  },
  {
    "classes": [
      "nulldelimiter"
    ],
    "style": "display:inline-block; width:.12em",
    "requiresKatex": true
  },
  {
    "classes": [
      "delimcenter"
    ],
    "style": "position:relative",
    "requiresKatex": true
  },
  {
    "classes": [
      "op-symbol"
    ],
    "style": "position:relative",
    "requiresKatex": true
  },
  {
    "classes": [
      "op-symbol",
      "small-op"
    ],
    "style": "font-family:KaTeX_Size1",
    "requiresKatex": true
  },
  {
    "classes": [
      "op-symbol",
      "large-op"
    ],
    "style": "font-family:KaTeX_Size2",
    "requiresKatex": true
  },
  {
    "classes": [
      "accent-body"
    ],
    "style": "position:relative; width:0",
    "requiresKatex": true
  },
  {
    "classes": [
      "overlay"
    ],
    "style": "display:block",
    "requiresKatex": true
  },
  {
    "classes": [
      "vertical-separator"
    ],
    "style": "display:inline-block; min-width:1px",
    "requiresKatex": true
  },
  {
    "classes": [
      "arraycolsep"
    ],
    "style": "display:inline-block",
    "requiresKatex": true
  },
  {
    "classes": [
      "svg-align"
    ],
    "style": "text-align:left",
    "requiresKatex": true
  },
  {
    "classes": [],
    "tag": "svg",
    "style": "fill:currentColor; stroke:currentColor; fill-rule:nonzero; fill-opacity:1; stroke-width:1; stroke-linecap:butt; stroke-linejoin:miter; stroke-miterlimit:4; stroke-dasharray:none; stroke-dashoffset:0; stroke-opacity:1; display:block; height:inherit; position:absolute; width:100%",
    "requiresKatex": true
  },
  {
    "classes": [],
    "tag": "path",
    "style": "stroke:none",
    "requiresKatex": true
  },
  {
    "classes": [],
    "tag": "img",
    "style": "border-style:none; max-height:none; max-width:none; min-height:0; min-width:0",
    "requiresKatex": true
  },
  {
    "classes": [
      "stretchy"
    ],
    "style": "display:block; overflow:hidden; position:relative; width:100%; content:\"\"; content:\"\"",
    "requiresKatex": true
  },
  {
    "classes": [
      "hide-tail"
    ],
    "style": "overflow:hidden; position:relative; width:100%",
    "requiresKatex": true
  },
  {
    "classes": [
      "halfarrow-left"
    ],
    "style": "left:0; overflow:hidden; position:absolute; width:50.2%",
    "requiresKatex": true
  },
  {
    "classes": [
      "halfarrow-right"
    ],
    "style": "overflow:hidden; position:absolute; right:0; width:50.2%",
    "requiresKatex": true
  },
  {
    "classes": [
      "brace-left"
    ],
    "style": "left:0; overflow:hidden; position:absolute; width:25.1%",
    "requiresKatex": true
  },
  {
    "classes": [
      "brace-center"
    ],
    "style": "left:25%; overflow:hidden; position:absolute; width:50%",
    "requiresKatex": true
  },
  {
    "classes": [
      "brace-right"
    ],
    "style": "overflow:hidden; position:absolute; right:0; width:25.1%",
    "requiresKatex": true
  },
  {
    "classes": [
      "x-arrow-pad"
    ],
    "style": "padding:0 .5em",
    "requiresKatex": true
  },
  {
    "classes": [
      "cd-arrow-pad"
    ],
    "style": "padding:0 .55556em 0 .27778em",
    "requiresKatex": true
  },
  {
    "classes": [
      "mover"
    ],
    "style": "text-align:center",
    "requiresKatex": true
  },
  {
    "classes": [
      "munder"
    ],
    "style": "text-align:center",
    "requiresKatex": true
  },
  {
    "classes": [
      "x-arrow"
    ],
    "style": "text-align:center",
    "requiresKatex": true
  },
  {
    "classes": [
      "boxpad"
    ],
    "style": "padding:0 .3em",
    "requiresKatex": true
  },
  {
    "classes": [
      "fbox"
    ],
    "style": "border:.04em solid; box-sizing:border-box",
    "requiresKatex": true
  },
  {
    "classes": [
      "fcolorbox"
    ],
    "style": "border:.04em solid; box-sizing:border-box",
    "requiresKatex": true
  },
  {
    "classes": [
      "cancel-pad"
    ],
    "style": "padding:0 .2em",
    "requiresKatex": true
  },
  {
    "classes": [
      "cancel-lap"
    ],
    "style": "margin-left:-.2em; margin-right:-.2em",
    "requiresKatex": true
  },
  {
    "classes": [
      "sout"
    ],
    "style": "border-bottom-style:solid; border-bottom-width:.08em",
    "requiresKatex": true
  },
  {
    "classes": [
      "angl"
    ],
    "style": "border-right:.049em solid; border-top:.049em solid; box-sizing:border-box; margin-right:.03889em",
    "requiresKatex": true
  },
  {
    "classes": [
      "anglpad"
    ],
    "style": "padding:0 .03889em",
    "requiresKatex": true
  },
  {
    "classes": [
      "eqn-num"
    ],
    "style": "content:\"(\" counter(katexEqnNo) \")\"; counter-increment:katexEqnNo",
    "requiresKatex": true
  },
  {
    "classes": [
      "mml-eqn-num"
    ],
    "style": "content:\"(\" counter(mmlEqnNo) \")\"; counter-increment:mmlEqnNo",
    "requiresKatex": true
  },
  {
    "classes": [
      "mtr-glue"
    ],
    "style": "width:50%",
    "requiresKatex": true
  },
  {
    "classes": [
      "cd-vert-arrow"
    ],
    "style": "display:inline-block; position:relative",
    "requiresKatex": true
  },
  {
    "classes": [
      "cd-label-left"
    ],
    "style": "display:inline-block; position:absolute; right:calc(50% + .3em); text-align:left",
    "requiresKatex": true
  },
  {
    "classes": [
      "cd-label-right"
    ],
    "style": "display:inline-block; left:calc(50% + .3em); position:absolute; text-align:right",
    "requiresKatex": true
  },
  {
    "classes": [
      "katex-display"
    ],
    "style": "display:block; margin:1em 0; text-align:center",
    "requiresKatex": true
  },
  {
    "classes": [
      "katex-html"
    ],
    "style": "display:block; position:relative",
    "requiresKatex": true
  },
  {
    "classes": [
      "tag"
    ],
    "style": "position:absolute; right:0; left:0; right:auto",
    "requiresKatex": true
  },
  {
    "classes": [],
    "tag": "body",
    "style": "counter-reset:katexEqnNo mmlEqnNo",
    "requiresKatex": false
  }
]
