INSERT INTO reverse_engineering_logs (
  id,
  user_id,
  created_at,
  article_title,
  article_url,
  original_content,
  genre_category,
  reverse_result_json,
  final_system_prompt,
  metric_burstiness,
  metric_ttr,
  metric_avg_sent_len,
  model_name,
  total_tokens,
  cost_estimated_usd,
  n8n_execution_id,
  status
) VALUES (
  '708',
  'anonymous',
  DATETIME('now'),
  'Unknown Title',
  'https://mp.weixin.qq.com/s/test',
  '["test"]',
  'NEWS',
  '{"text":"```json\\n{\\n  \\"style_name\\": \\"Nostalgic Obituary Retrospective\\"\\n}\\n```"}',
  '',
  22.24,
  0.99,
  22.3,
  'gpt-4o-mini',
  0,
  0,
  '709',
  'SUCCESS'
);
