INSERT INTO reverse_engineering_logs (
  id,
  user_id,
  created_at,
  article_title,
  article_url,
  original_content,
  genre_category,
  reverse_result_json,
  final_system_prompt,
  metric_burstiness,
  metric_ttr,
  metric_avg_sent_len,
  model_name,
  total_tokens,
  cost_estimated_usd,
  n8n_execution_id,
  status
) VALUES (
  '707',
  'anonymous',
  DATETIME('now'),
  'Unknown Title',
  'https://mp.weixin.qq.com/s/JTIco9eNbHIVmUSTyqAK_A',
  '["人物||何晴香消玉殒，生得其时却也生不逢时的北影版红楼美人们……","原创"]',
  'NEWS',
  '{"text":"```json\n{\n  \"style_name\": \"Nostalgic Obituary Retrospective\",\n  \"meta_profile\": {\n    \"archetype\": \"Cultural Historian & Elegist\",\n    \"tone_keywords\": [\"reverent\", \"nostalgic\", \"detailed\", \"biographical\", \"fateful\"]\n  },\n  \"blueprint\": [\n    {\n      \"section\": \"Hook/Intro\",\n      \"specs\": \"Announce the subject''s death as the news peg. Immediately pivot to establishing their iconic status and cultural significance within a specific era or group (e.g., ''classical beauties of 80s Chinese cinema''). 1-2 paragraphs.\"\n    },\n    {\n      \"section\": \"Career & Legacy Anchor\",\n      \"specs\": \"Concisely list key career achievements and defining roles. Use this section to establish the subject''s professional stature and public image. 1 paragraph.\"\n    }\n  ],\n  \"constraints\": {\n    \"burstiness\": \"CRITICAL: Drastically reduce burstiness from 22+ to under 10.\",\n    \"vocabulary\": \"Use precise nouns for roles, films, and relationships.\",\n    \"formatting\": \"Paragraphs MUST be short, 1-3 sentences maximum.\"\n  },\n  \"execution_prompt\": \"You are a Senior Cultural Correspondent for a major news agency. Your task is to write a detailed, respectful obituary feature.\\n\\n[Constraints]\\n- **Burstiness:** Maintain a low, steady rhythm (<10).\\n- **Vocabulary:** Use precise terminology for films, roles, and institutions.\\n\\n[Style]\\nAdopt the tone of a ''Nostalgic Obituary Retrospective.'' Be reverent and detailed.\"\n}\n```"}',
  '',
  22.24,
  0.99,
  22.3,
  'gpt-4o-mini',
  0,
  0,
  '708',
  'SUCCESS'
);
