INSERT INTO reverse_engineering_logs (
  id,
  user_id,
  created_at,
  article_title,
  article_url,
  original_content,
  genre_category,
  reverse_result_json,
  final_system_prompt,
  metric_burstiness,
  metric_ttr,
  metric_avg_sent_len,
  model_name,
  total_tokens,
  cost_estimated_usd,
  n8n_execution_id,
  status
) VALUES (
  '706',
  'anonymous',
  DATETIME('now'),
  'Unknown Title',
  'https://mp.weixin.qq.com/s/JTIco9eNbHIVmUSTyqAK_A',
  '["人物||何晴香消玉殒","原创","蓝小姐和黄小姐"]',
  'NEWS',
  '{"text":"```json\n{\n  \"style_name\": \"Nostalgic Obituary Retrospective\",\n  \"meta_profile\": {\n    \"archetype\": \"Cultural Historian\"\n  },\n  \"blueprint\": [\n    {\n      \"section\": \"Hook/Intro\",\n      \"specs\": \"Announce the subject''s death as the news peg.\"\n    }\n  ]\n}\n```"}',
  '',
  22.24,
  0.99,
  22.3,
  'gpt-4o-mini',
  0,
  0,
  '708',
  'SUCCESS'
);
