"use client"

import {
  A2UIColumn,
  A2UIRow,
  A2UIContainer,
  A2UIScrollArea,
  A2UICard,
  A2UIPage,
  A2UINav,
  A2UINavLink,
  A2UISpacer,
} from "./layout"
import { A2UIText } from "./typography"
import { A2UIImage, A2UIIcon, A2UIDivider, A2UILink } from "./content"
import {
  A2UIButton,
  A2UIInput,
  A2UIEditableText,
  A2UITextarea,
  A2UISelect,
  A2UICheckbox,
  A2UITabs,
  A2UIForm,
  A2UIFormField,
  A2UICollapsible,
} from "./interactive"
import {
  A2UIBadge,
  A2UIProgress,
  A2UIModal,
  A2UIAlert,
  A2UIFallback,
} from "./feedback"

export {
  A2UIColumn,
  A2UIRow,
  A2UIContainer,
  A2UIScrollArea,
  A2UICard,
  A2UIPage,
  A2UINav,
  A2UINavLink,
  A2UISpacer,
  A2UIText,
  A2UIImage,
  A2UIIcon,
  A2UIDivider,
  A2UILink,
  A2UIButton,
  A2UIInput,
  A2UIEditableText,
  A2UITextarea,
  A2UISelect,
  A2UICheckbox,
  A2UITabs,
  A2UIForm,
  A2UIFormField,
  A2UICollapsible,
  A2UIBadge,
  A2UIProgress,
  A2UIModal,
  A2UIAlert,
  A2UIFallback,
}

export const CoreComponents = {
  column: A2UIColumn,
  row: A2UIRow,
  container: A2UIContainer,
  "scroll-area": A2UIScrollArea,
  card: A2UICard,
  text: A2UIText,
  image: A2UIImage,
  icon: A2UIIcon,
  divider: A2UIDivider,
  button: A2UIButton,
  input: A2UIInput,
  "editable-text": A2UIEditableText,
  textarea: A2UITextarea,
  select: A2UISelect,
  checkbox: A2UICheckbox,
  tabs: A2UITabs,
  badge: A2UIBadge,
  progress: A2UIProgress,
  modal: A2UIModal,
  alert: A2UIAlert,
  page: A2UIPage,
  nav: A2UINav,
  "nav-link": A2UINavLink,
  spacer: A2UISpacer,
  link: A2UILink,
  form: A2UIForm,
  "form-field": A2UIFormField,
  collapsible: A2UICollapsible,
}
